require("core.options")
require("core.plugins")
require("core.mappings")
require("core.colorscheme")

require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.comments")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
