require("core.options")
require("core.plugins")
require("core.mappings")
require("core.colorscheme")

require("plugins.tree")
require("plugins.buffline")
require("plugins.comments")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.mason")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.dashboard")
